on: push
name: LARAVEL DUSK
jobs:
  dusk:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:7.3.0
      options: --shm-size=2048M --cpus 2

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Install chrome
        run: |
          apt-get update
          apt-get install -y libnss3 chromium-browser --fix-missing
          apt-get -y install libxpm4 libxrender1 libgtk2.0-0 \
          libnss3 libgconf-2-4 chromium-browser \
          xvfb gtk2-engines-pixbuf xfonts-cyrillic \
          xfonts-100dpi xfonts-75dpi xfonts-base \
          xfonts-scalable imagemagick x11-apps
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          composer install --no-scripts --ignore-platform-reqs
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Update npm
        run: npm install -g npm@latest

      - name: Create DB and schemas
        working-directory: database
        run: |
          touch database.sqlite
      - name: Copy .env
        run: |
          cp .env.dusk.ci .env
          php artisan key:generate
          php artisan migrate
          php artisan optimize
      - name: Upgrade Chrome Driver
        run: |
          php artisan dusk:update
          php artisan dusk:chrome-driver 72

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux

      - name: Run Laravel Server
        run: php artisan serve --host=som.test --port=8000

      - name: Run Dusk Tests
        run: php artisan dusk

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: screenshots
          path: tests/Browser/screenshots

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: logs
          path: storage/logs
